// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id int32) error
	// Returns a single struct. Errors if ID is not found.
	GetProduct(ctx context.Context, id int32) (Product, error)
	// Returns a slice of structs. Returns empty slice if no products exist.
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
